### ISSUE TITLE
请问能否提供mysql数据库版本呢？

### ISSUE THREAD

**Issue by souvc** [modood/Administrative-divisions-of-China#10]

**Comment by modood** [comment]
这个 Fork 增加了 MySQL 入库操作，你可以参考一下：
https://github.com/icai/Administrative-divisions-of-China

**Comment by zhangxsheng** [comment]
https://github.com/zhangxsheng/Administrative-divisions-of-China这个Fork增加了SQL的脚本

**Comment by modood** [comment]
@souve 您好，最近一次更新已经将数据保存到 sqlite3 中，如需支持 MySQL，可以自行将数据由 sqlite3 迁移到 MySQL，详情请看 README 文件。
