### ISSUE TITLE
npm run fetch乱码报错

### ISSUE THREAD

**Issue by b395612437** [modood/Administrative-divisions-of-China#100]
![image](https://user-images.githubusercontent.com/25102030/123044112-d197c980-d42b-11eb-8e5f-7838a5ae7a4d.png)

**Comment by pan102887** [comment]
这是你的控制台的问题吧

**Comment by b395612437** [comment]
> 这是你的控制台的问题吧

什么意思，我不是很懂？我需要怎么调整

**Comment by b395612437** [comment]
我是把dist里面的文件全删除再跑的

**Comment by LarchLiu** [comment]
gzip 未解码,参考#98
