### ISSUE TITLE
No matching version found for china-division@2.4.0

### ISSUE THREAD

**Issue by Noemi-** [modood/Administrative-divisions-of-China#102]
直接通过npm升级china-division到2.4.0的时候报错。
命令：npm install -S china-division@2.4.0
报错：
npm ERR! code ETARGET
npm ERR! notarget No matching version found for china-division@2.4.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by Noemi-** [comment]
请问是因为没有把2.4.0发布到npm上吗？有计划发布吗？

**Comment by modood** [comment]
@Noemi- 刚刚已发布。 a3d1a730bb5248bdb008d3cf38d8277cf54b73e3
