### ISSUE TITLE
部分区域名称乱码

### ISSUE THREAD

**Issue by alvisisme** [modood/Administrative-divisions-of-China#106]
网站上有部分数据中文乱码，比如 江西省-吉安市-新干县-麦斜镇

http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2020/36/08/360824.html

导致抓取的数据显示？，可能需要手动打补丁修复一下

360824104,"麦?镇",360824,36,3608

**Comment by modood** [comment]
http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2021/36/08/360824.html
国家统计局最新发布数据已经修复，待项目数据更到最新即可解决。
