### ISSUE TITLE
爬虫获取的中山市和东莞市数据有问题-在区域的文件（areas.json）中

### ISSUE THREAD

**Issue by githubyyf** [modood/Administrative-divisions-of-China#11]
![image](https://user-images.githubusercontent.com/21100974/28150539-aa919674-67c7-11e7-9c52-eab6e72d4ae2.png)

在区域的文件中（areas.json）中，最后两条数据是有问题，code码和parent_code相同但中山市和东莞市是市级的在city中已经存在。

**Comment by modood** [comment]
您好，中山市和东莞市比较特殊，这里是单独处理的。

因为中山市和东莞市没有 “区县” 级行政区划，目前的处理是以父级 “城市” 名称填充。

比如和广州市作为对比：

| 省份 | 城市 | 区县 | 乡镇 |
|:-------|:-------|:------:|:-------|
| 广东省 | 广州市 | 花都区 | 花山镇 |
| 广东省 | 中山市 |- | 横栏镇 |
| 广东省 | 东莞市 |- | 大朗镇 |

**Comment by githubyyf** [comment]
如果parentCode=code那还有必要存在吗？
