### ISSUE TITLE
缺少了大量的市辖区

### ISSUE THREAD

**Issue by YumeMichi** [modood/Administrative-divisions-of-China#12]
整个河北省的市辖区几乎全部没有。

**Comment by YumeMichi** [comment]
看了一下提交记录发现是这里去掉了

**Comment by YumeMichi** [comment]
我自己fork了一份仅作为自己的特殊需要

**Comment by modood** [comment]
@YumeMichi 你好，因为这里市辖区不属于具体的某个区，所以特意过滤掉了。所以像你说的可以 fork 一份根据具体需求进行修改。

**Comment by huageorg** [comment]
> @YumeMichi 你好，因为这里市辖区不属于具体的某个区，所以特意过滤掉了。所以像你说的可以 fork 一份根据具体需求进行修改。

我觉得不应该过滤掉，因为统计局网站上是没有过滤的，是平级的，要保留才完整。

**Comment by modood** [comment]
“市辖区”无法明确到具体哪个区。“市辖区”的概念类似于“县级市”、“县”等县级行政区，是一种统称。

> 截至 2018 年 9 月 20 日，中国（含香港、澳门特别行政区，不含台湾省，内地 970 个市辖区）共计 996 个市辖区。
例如河北省一共设立了 47 个市辖区，其中石家庄市下有 8 个，分别是：
长安区、桥西区、新华区、井陉矿区、裕华区、藁城区、鹿泉区、栾城区
他们都属于市辖区。

如果有特殊需要需要保留，可以 fork 本项目将过滤去掉即可。
@huageorg

**Comment by snakejordan** [comment]
fork 了项目，发现大量没有市辖区并不是过滤掉的问题。
例如2018年版本的[安徽省](http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/34.html)，下级所有的市都是有市辖区的，例如[合肥市](http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/34/3401.html)。

代码里面发现因为这些市辖区并非是有下级超链接的，所以在crawler.js里面的正则表达式匹配就不能匹配到。

合肥市页面源码：
![image](https://user-images.githubusercontent.com/3376284/55159453-0446af00-519c-11e9-92ec-653737f1e874.png)

crawler.js源码：
![image](https://user-images.githubusercontent.com/3376284/55159530-31935d00-519c-11e9-991d-49fbbc3b2981.png)

由于对 NodeJS 和正则都不是很拿手，所以想请教如何能做到在这段“地级、县级、乡级”的正则里面包括漏掉的直辖市信息？
