### ISSUE TITLE
怎么导入mysql?

### ISSUE THREAD

**Issue by Formerscholar** [modood/Administrative-divisions-of-China#121]
怎么导入mysql?

**Comment by xiangyuecn** [comment]
@xiaodaoM 我库里面提供了一个转换工具，可以把csv格式的数据导入数据库，不过只支持省市区乡镇4级，不支持村级

https://github.com/xiangyuecn/AreaCity-JsSpider-StatsGov

**Comment by modood** [comment]
https://www.google.com/search?q=sqlite+to+mysql
