### ISSUE TITLE
国家统计局数据带?号了...但是百科可以查到，爬取的得判断下

### ISSUE THREAD

**Issue by nn200433** [modood/Administrative-divisions-of-China#124]
```
522626001 
522626001001
500153108200

这几个区划名称有?号（国家统计局的问题）
```

![image](https://user-images.githubusercontent.com/15652213/184587216-90ba8fc3-2dcf-4714-a108-456285015f65.png)

![image](https://user-images.githubusercontent.com/15652213/184587243-3d99c953-4fe6-4f2a-935a-4bf6245111b3.png)

**Comment by cvpv** [comment]
国家统计局这么不严谨字库没有这个字吗？

**Comment by nn200433** [comment]
> 国家统计局这么不严谨字库没有这个字吗？

也不是，应该是生僻字（拿个同音相近字代替）。发现有些地方字库还真没有...

**Comment by modood** [comment]
国家统计局最新数据（2022）已经解决这个问题
http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2022/52/26/522626.html

**Comment by aixcyi** [comment]
最新数据只解决了部分地名，仍有一些地名是?，需要注意一下。
http://www.stats.gov.cn/sj/tjbz/tjyqhdmhcxhfdm/2022/50/01/53/500153108.html
