### ISSUE TITLE
四级联动数据能加上行政区划代码吗？

### ISSUE THREAD

**Issue by jingxinxin** [modood/Administrative-divisions-of-China#13]
地区可能重名，但行政区划代码不会，数据库也好存

**Comment by ibrucekong** [comment]
同问能不能加上行政区划代码，那种12位数的代码，比如[510100000000:成都]

**Comment by modood** [comment]
@jingxinxin @ibrucekong 最近很多人提到这个，既然都需要，近期会加上 code，请持续关注。

**Comment by modood** [comment]
已经加上带编码的联动数据。
详见：https://github.com/modood/Administrative-divisions-of-China#json
