### ISSUE TITLE
加入抓取时间等信息

### ISSUE THREAD

**Issue by bruceleedrupal** [modood/Administrative-divisions-of-China#14]
因为数据需要不断抓取,建议在抓取文件里加入抓取时间等信息,方便了解数据的新旧程度,鉴于json没有comment,建议将日期直接以属性值的方式加入,譬如这种

`{
   "_comment" : "comment text goes here...",
  "address":[.......]
}`

**Comment by modood** [comment]
多次抓取数据都是不变的，因为数据是按年更新的，因此暂时没有这个必要
