### ISSUE TITLE
街道信息，可能有部分数据缺失

### ISSUE THREAD

**Issue by stxpons** [modood/Administrative-divisions-of-China#142]
比如，江苏省南京市建邺区，代码：320105。
名下应有10个四级街道：
https://www.stats.gov.cn/sj/tjbz/tjyqhdmhcxhfdm/2022/32/01/320105.html

但其实streets.csv文件里，只有6条数据

**Comment by stxpons** [comment]
2023年的缺失少了几条

**Comment by modood** [comment]
@stxpons 每年数据更新是有一些差异的，以最新数据为准哈
https://www.stats.gov.cn/sj/tjbz/tjyqhdmhcxhfdm/2023/32/01/320105.html
