### ISSUE TITLE
数据重复

### ISSUE THREAD

**Issue by fluxyster** [modood/Administrative-divisions-of-China#15]
https://raw.githubusercontent.com/modood/Administrative-divisions-of-China/master/dist/pcas-code.json 
其中

东莞市 441900
中山市 442000
儋州市 460400

三项数据都有重复的结点,对于数据库导入是个问题

**Comment by fluxyster** [comment]
为保持层次的一致性,建议对这几个进行重新编码,譬如同一个东莞市设两个,id不同

**Comment by fluxyster** [comment]
东莞市 441900 > 市辖区 44190001
中山市 442000 > 市辖区 44200001
儋州市 460400 > 市辖区  46040001
 
用统一的市辖区作为名称可以更方便的在程序中替换显示

**Comment by fluxyster** [comment]
香港和澳门的数据不完整

**Comment by fluxyster** [comment]
最好还是将
东莞市 441900
中山市 442000
儋州市 460400
这几个的中间层数据删掉

**Comment by modood** [comment]
@fluxyster 您好，已经在最新的代码中解决了东莞市、中山市、儋州市二级三级 code 重复的问题，并且重新抓取了数据，解决方案为：区划代码位数规范化。
*   省级：2 位
*   地级：4 位
*   县级：6 位
*   乡级：9 位

关于“香港和澳门台湾的数据不完整”，这部分数据待补全，请持续关注。

**Comment by fluxyster** [comment]
非常感谢您这么快做了迅速调整!关于这个调整,几个小问题想再跟您沟通下:
1.
东莞市 441900
中山市 442000
儋州市 460400
这三个地址的中文名能否直接全部改成 市辖区,这样在输出完整地址时不会同一名称出现两次,另外使用统一的市辖区方便程序直接匹配过滤 ( 另外一种解决方案是直接删除这几个中间层,相当于这些是三级联动数据,这样能够保证数据的精简)

2.港澳台数据我从淘宝地址里手工整理了一份,编码长度跟你保持一致,为json数组格式,一级有code 的index,方便进行合并,其中澳门为二级,港台为三级,所以我建议前面的三个城市中间层删掉,因为属于多少层级能够通过程序自动提取,这不是个问题

再次感谢您的付出,这个地址库非常重要,如果需要我做什么我愿为效劳

[gat.json.zip](https://github.com/modood/Administrative-divisions-of-China/files/1328534/gat.json.zip)

**Comment by modood** [comment]
@fluxyster 您好，十分感谢您提供的宝贵意见和详细的港澳台数据，并且感谢您对本项目的关注和认可。

1.  关于中山东莞儋州三市的县级名称调整，我会继续收集更多意见，基于权威性和实用性加以考虑，可能后续版本会有所调整。目前您可以 fork 到自己的项目主页基于您的使用场景进行相应调整。

2.  非常感谢您提供的港澳台数据，我下载下来并且认真地看了一下，整理得非常细心非常有用。其实直到现在我一直未整理港澳台数据主要是因为暂时没有找到比较具有权威性的数据来源以及官方性的行政区划编码。如果未来要整理港澳台行政区划数据的话，相对于淘宝，我可能更认可来自维基百科的数据：

    * [维基百科-臺灣行政區劃](https://zh.wikipedia.org/wiki/%E8%87%BA%E7%81%A3%E8%A1%8C%E6%94%BF%E5%8D%80%E5%8A%83)
    * [维基百科-香港行政區劃](https://zh.wikipedia.org/wiki/%E9%A6%99%E6%B8%AF%E8%A1%8C%E6%94%BF%E5%8D%80%E5%8A%83)
    * [维基百科-澳門行政區劃](https://zh.wikipedia.org/wiki/%E6%BE%B3%E9%96%80%E8%A1%8C%E6%94%BF%E5%8D%80%E5%8A%83)

**Comment by fluxyster** [comment]
呵呵,我参考了几个和你类似的地址数据项目,感觉你这个较为不错,希望以后越来越好.

另外有个小问题我补充下,这几个新加地址的最下级镇一级地址应该是9位数,像东莞这几个后面好多0,超过9位了,腾讯地图api返回代码中有这个区域id,譬如东莞的 樟木头镇:

http://apis.map.qq.com/ws/district/v1/search?keyword=%E6%A8%9F%E6%9C%A8%E5%A4%B4%E9%95%87&key=D7RBZ-LKSRR-BELWR-WOKDN-E56EV-RFBAD

返回
`{
    "status": 0,
    "message": "query ok",
    "data_version": "20170824",
    "result": [
        [
            {
                "id": "441900112",
                "fullname": "樟木头镇",
                "level": 4,
                "location": {
                    "lat": 22.89895,
                    "lng": 114.092424
                },
                "address": "广东,东莞,东莞市,樟木头镇"
            }
        ]
    ]
}`

**Comment by modood** [comment]
@fluxyster 感谢指出，遗漏的街道数据编码位数处理已修复[3e78d8a](https://github.com/modood/Administrative-divisions-of-China/commit/3e78d8a6022aa439bf82d2cb699370330489cd59)
