### ISSUE TITLE
省直辖县级行政区划不在pc.json里

### ISSUE THREAD

**Issue by PengyuanZhao** [modood/Administrative-divisions-of-China#18]
我只需要用`“省份、城市” 二级联动数据 pc.json`来选择省份和城市，但是里面没有省直辖县级行政区。

比如如果我生活在河南省济源市，用pc.json就找不到这个地方。

**Comment by modood** [comment]
@PengyuanZhao 感谢指出！根据 [国家统计局数据](http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/201703/t20170310_1471429.html) 这个城市属于区县级行政区划。但是出于实用性考虑，这两天我会收集更多意见，可能会将类似的 “省直辖县级行政区划” 数据添加到 “省份、城市” 二级联动数据中去，请保持关注！

**Comment by modood** [comment]
@PengyuanZhao 已经加上了 :smile:

**Comment by PengyuanZhao** [comment]
@modood  谢谢！速度好快 👍
