### ISSUE TITLE
数据准确性有问题

### ISSUE THREAD

**Issue by sixinyiyu** [modood/Administrative-divisions-of-China#19]
你这爬出来的数据已经跟真实的不一样了；有些县升级成地市了；没有特殊处理；有些地市code、名字都变化了；那个统计的网站没更新；不过发了通知；导致没同步到最新的行政信息

**Comment by modood** [comment]
@sixinyiyu 国家统计局的 “区划全年变更文件（[县以上](http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/)、[县以下](http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/)）”每年发布一次，而在国家民政部每个月都会发布的 [行政区划变更情况](http://www.mca.gov.cn/article/sj/tjbz/a/2017/) 中，县以下数据的变更太零碎不好抓取进行个别更新，因为县以上和县以下行政区划必须是分开抓取的，所以为了保证 “区县” 和 “乡镇” 在大的范围内保持一致性，本项目目前是跟随国家统计局的数据按年更新，后续优化版本可能会根据民政部数据进行更实时地更新。如果你觉得还是太滞后无法满足你的需求，你可以自己撸一套。或者你有更实时的数据来源，欢迎提供。：）
