### ISSUE TITLE
缺少非直辖市，市辖区行政编码

### ISSUE THREAD

**Issue by xyy94813** [modood/Administrative-divisions-of-China#20]
国家统计局上，非直辖市包含市辖区行政编码
eg：130101 河北省 石家庄市 市辖区

但是抓取下来的数据没有

**Comment by modood** [comment]
@xyy94813 您好，市辖区并非指特定的某个区，比如说石家庄市的“长安区”、“桥西区”和“新华区”等都属于市辖区，出于实用性考虑是特意过滤掉 “市辖区” 这个名称了的。不知道您需要这个有什么特定用处吗？

**Comment by xyy94813** [comment]
@modood 下午 review 代码的时候看到了这个功能。因为 README 文档里没有提及，我以为是个bug。

另外，项目里有用到 yarn ，README 中提及的是使用 npm，新版 npm 会产生 package-lock.json。

**Comment by modood** [comment]
@xyy94813 感谢指出，后面版本会有所优化。:smile:

**Comment by modood** [comment]
参考 #12
