### ISSUE TITLE
国家统计局数据滞后于民政部数据

### ISSUE THREAD

**Issue by ryh** [modood/Administrative-divisions-of-China#21]
http://www.mca.gov.cn/article/sj/tjbz/a/
但mca又没有完整的县以下的数据，有人能以大公司的名义请求mca 公开县以下的数据么

**Comment by modood** [comment]
@ryh 你好，stats 的数据每年发布一次，而 mca 每个月都会发布[变更情况](http://www.mca.gov.cn/article/sj/tjbz/a/2017/) ，但是这里边的数据太零碎了不好抓取，因此目前我都是仅抓取每年发布的稳定版本，暂时无法与 mca 实时同步。如果你想到比较好的解决方案，非常欢迎告知！ :smile:

**Comment by ryh** [comment]
mca又没有完整的县以下的数据，所以估计技术上不可能实现，所以我的建议是“有人能以大公司的名义请求mca 公开县以下的数据” 😂

**Comment by huageorg** [comment]
这个是统计局自己的数据，用于官方统计使用的。

**Comment by whyshrha** [comment]
您好，可以发布下14年的数据吗，因为科研用到了14年数据，我会科学引用您的github链接。

**Comment by modood** [comment]
@whyshrha 您好，由于这种需求比较小众暂时不在这个项目里提供。你可以将项目 fork 下来修改指定年份后重新抓取数据即可，或者 fork 下来后给我加上权限我帮你修改抓取。
