### ISSUE TITLE
需要五级村委会的，请给予支持

### ISSUE THREAD

**Issue by hackgyj** [modood/Administrative-divisions-of-China#23]
感谢感谢。

**Comment by modood** [comment]
@hackgyj 您好，第五级行政区划详细到居委会了，对于一般需求来说用处不大，但是数据量极大，因此暂时不考虑。如果确实有需要，可以 fork 项目参考源码，到国家统计局抓取，原理都是一样的。

**Comment by modood** [comment]
@hackgyj 您好，最近一次更新已经支持第五级数据了，详情请看 README 文件。

**Comment by zhangnew** [comment]
@modood 你好，有考虑出第五级联动数据吗？

**Comment by zhangnew** [comment]
> 你好，已经提供第五级数据了，由于数据量较多，建议五级联动由后端查询数据库实现

@modood 好的，感谢
