### ISSUE TITLE
省，市，县区数据抓取不到了

### ISSUE THREAD

**Issue by wanjidong** [modood/Administrative-divisions-of-China#24]
如题，网址找不到了:
http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/201703/t20170310_1471429.html

**Comment by modood** [comment]
@wanjidong 感谢指出，[打开这个地址](http://www.stats.gov.cn/tjsj/tjbz/)可以看到国家统计局已经将这一块内容下线了

**旧的页面（来自百度快照）**：
![image](https://user-images.githubusercontent.com/11327898/35549642-72be5cee-05c1-11e8-889a-dccbc934d01a.png)

**最新页面**：
![image](https://user-images.githubusercontent.com/11327898/35549696-abf8a730-05c1-11e8-9431-a1b4e0f61e31.png)

如果这两天没有恢复的话，我会将抓取的数据源改为国家民政部发布的数据，请保持关注。:smile:

**Comment by wanjidong** [comment]
我尝试用民政部的数据抓取了，好多数据对不上。^_^

**Comment by modood** [comment]
> 直接抓统计页面数据吧:http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2016/index.html

@wanjidong 已更新，已经采纳你的建议直接抓取这个页面，并且第五级（村级）数据也抓取了，更多变动详情请看 README 文件。

**Comment by wanjidong** [comment]
非常感谢，我试试，这个给大家提供了很大的方便，非常感谢~！
