### ISSUE TITLE
成都 高新区 天府新区没有啊?

### ISSUE THREAD

**Issue by engome** [modood/Administrative-divisions-of-China#25]
成都 高新区 天府新区没有啊?

**Comment by leopoo** [comment]
谢谢

**Comment by modood** [comment]
截至2018年6月，中国国家级新区总数共有19个。

中国国家级新区一览表：

| 序号 | 名称         | 获批时间       | 主体城市       |
|:-----|:-------------|:---------------|:---------------|
| 01   | 浦东新区     | 1992年10月11日 | 上海           |
| 02   | 滨海新区     | 2006年05月26日 | 天津           |
| 03   | 两江新区     | 2010年05月05日 | 重庆           |
| 04   | 舟山群岛新区 | 2011年06月30日 | 浙江舟山       |
| 05   | 兰州新区     | 2012年08月20日 | 甘肃兰州       |
| 06   | 南沙新区     | 2012年09月06日 | 广东广州       |
| 07   | 西咸新区     | 2014年01月06日 | 陕西西安、咸阳 |
| 08   | 贵安新区     | 2014年01月06日 | 贵州贵阳、安顺 |
| 09   | 西海岸新区   | 2014年06月03日 | 山东青岛       |
| 10   | 金普新区     | 2014年06月23日 | 辽宁大连       |
| 11   | 天府新区     | 2014年10月02日 | 四川成都、眉山 |
| 12   | 湘江新区     | 2015年04月08日 | 湖南长沙       |
| 13   | 江北新区     | 2015年06月27日 | 江苏南京       |
| 14   | 福州新区     | 2015年08月30日 | 福建福州       |
| 15   | 滇中新区     | 2015年09月07日 | 云南昆明       |
| 16   | 哈尔滨新区   | 2015年12月16日 | 黑龙江哈尔滨   |
| 17   | 长春新区     | 2016年02月03日 | 吉林长春       |
| 18   | 赣江新区     | 2016年06月14日 | 江西南昌、九江 |
| 19   | 雄安新区     | 2017年04月01日 | 河北保定       |
