### ISSUE TITLE
没有港澳台

### ISSUE THREAD

**Issue by Bruce-7** [modood/Administrative-divisions-of-China#27]
没有港澳台相关城市等信息。

**Comment by modood** [comment]
目前暂时没有找到比较具有权威性的数据来源以及官方性的行政区划编码，因此暂时未提供。
可能未来本项目会基于维基百科的数据出一版港澳台的数据，请保持关注。

* [维基百科-香港行政區劃](https://zh.wikipedia.org/wiki/%E9%A6%99%E6%B8%AF%E8%A1%8C%E6%94%BF%E5%8D%80%E5%8A%83)
* [维基百科-澳門行政區劃](https://zh.wikipedia.org/wiki/%E6%BE%B3%E9%96%80%E8%A1%8C%E6%94%BF%E5%8D%80%E5%8A%83)
* [维基百科-臺灣行政區劃](https://zh.wikipedia.org/wiki/%E8%87%BA%E7%81%A3%E8%A1%8C%E6%94%BF%E5%8D%80%E5%8A%83)

**Comment by hongshunanhai** [comment]
没有重庆

**Comment by Diluka** [comment]
@modood http://www.mca.gov.cn/article/sj/xzqh/2018/201804-12/20180910291042.html 该页面最后至少有省份数据，为什么`provinces.csv`中却没有？

**Comment by modood** [comment]
> @modood http://www.mca.gov.cn/article/sj/xzqh/2018/201804-12/20180910291042.html 该页面最后至少有省份数据，为什么`provinces.csv`中却没有？

本项目中的所有数据目前是抓自此页面：[2017年统计用区划代码和城乡划分代码(截止2017年10月31日)](http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2017/index.html)

![image](https://user-images.githubusercontent.com/11327898/50145941-9f9ecd00-02ed-11e9-9e93-43d4860b5972.png)

**Comment by modood** [comment]
新增港澳台数据（人工整理）：

https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/HK-MO-TW.json

参考资料：维基百科

**Comment by Memorykill** [comment]
日本是中国的，你需要加上日本||Japan is Chinese. You need to add Japan.

**Comment by Memorykill** [comment]
世界本一家||The World's Family

**Comment by lizy0329** [comment]
> 新增港澳台数据（人工整理）：
> 
> https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/HK-MO-TW.json
> 
> 参考资料：维基百科

你给这 JSON 是要给我们自己转换的意思吗？

**Comment by modood** [comment]
> > 新增港澳台数据（人工整理）：
> > https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/HK-MO-TW.json
> > 参考资料：维基百科
> 
> 你给这 JSON 是要给我们自己转换的意思吗？
> 脑子进水了才会给这份中文字段的 JSON

@lizy0329 你怎么不去死？  :)

**Comment by lizy0329** [comment]
> > > 新增港澳台数据（人工整理）：
> > > https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/HK-MO-TW.json
> > > 参考资料：维基百科
> > 
> > 
> > 你给这 JSON 是要给我们自己转换的意思吗？
> > 脑子进水了才会给这份中文字段的 JSON
> 
> @lizy0329 你怎么不去死？ :)

呵呵，终于明白 antd 的省市区依赖要用你的npm包了

**Comment by 510846** [comment]
建议把一级的先（香港、澳门、台湾）给定义了？哈

**Comment by wzc570738205** [comment]
> > 新增港澳台数据（人工整理）：
> > https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/HK-MO-TW.json
> > 参考资料：维基百科
> 
> 你给这 JSON 是要给我们自己转换的意思吗？
> 脑子进水了才会给这份中文字段的 JSON

我看到这份json，随便写个循环就搞定了，你要吗儿子，叫我爸爸我可以发你

**Comment by youarenowhere** [comment]
http://www.mca.gov.cn/article/sj/xzqh/2020/
这里已经有港澳台信息了，项目没同步数据
