### ISSUE TITLE
fetch 350527000 stop

### ISSUE THREAD

**Issue by oxygenpresident** [modood/Administrative-divisions-of-China#28]
获取福建金门县时，由于不存在而停止。
建议特殊处理

**Comment by modood** [comment]
@oxygenpresident  您好，经多次尝试都没有出现这种情况，如果问题依旧存在，您可以提供更多详细的调试信息

**Comment by vipcxj** [comment]
我这边也卡在这个code，一开始还是404，无限重试后就变成403了，希望能重写open这个issue

**Comment by vipcxj** [comment]
http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2017/35/3505.html
金门县确实是没链接的，超链接是黑色的，网上查了下，这个地方貌似是台湾在管理，所以才没有数据吧，希望能特殊处理，或者教下怎么改源码来特殊处理也好

**Comment by vipcxj** [comment]
又看了下源码，350527000确实有特殊处理，但是没有起效。我的操作步骤是：
1. clone 源码
2. npm i
3. npm run fetch
难道我的操作步骤有什么问题吗？

**Comment by modood** [comment]
@vipcxj 你好，如果问题依然存在，尝试把 dist 目录里的数据清一下，然后重新抓取试试。
可以的话提供一下截图，更方便定位问题

**Comment by vipcxj** [comment]
疯狂重试会导致被禁止链接那个网站，只能等明天再试了

**Comment by vipcxj** [comment]
抓取省级数据失败（Error: Request Failed. Status Code: 403），正在重试...
抓取省级数据失败（Error: Request Failed. Status Code: 403），正在重试...
抓取省级数据失败（Error: Request Failed. Status Code: 403），正在重试...
抓取省级数据失败（Error: Request Failed. Status Code: 403），正在重试...
抓取省级数据失败（Error: Request Failed. Status Code: 403），正在重试...
抓取省级数据失败（Error: Request Failed. Status Code: 403），正在重试...
抓取省级数据失败（Error: Request Failed. Status Code: 403），正在重试...
抓取省级数据失败（Error: Request Failed. Status Code: 403），正在重试...
抓取省级数据失败（Error: Request Failed. Status Code: 403），正在重试...
抓取省级数据失败（Error: Request Failed. Status Code: 403），正在重试...
抓取省级数据失败（Error: Request Failed. Status Code: 403），正在重试...
抓取省级数据失败（Error: Request Failed. Status Code: 403），正在重试...

无限刷这个，一开始应该是404，这样几次之后就变成403了，但重试太多，找不到历史打印数据了

**Comment by vipcxj** [comment]
@modood 我删了dist里面所有东西，直接就不能运行了～ build也不能build

**Comment by modood** [comment]
> @modood 我删了dist里面所有东西，直接就不能运行了～ build也不能build

`/bin/rm -f dist/* && npm run fetch` 这样应该是可以的，有什么报错信息吗？

**Comment by vipcxj** [comment]
报找不到数据库文件的问题，我是直接删了dist文件夹，然后报错，于是我重新建了空的dist文件夹，还是同样错，错误暂时找不到了，我目前reset了head，恢复了dist，然后改了下源码，在fetchStreet里也对areaCode === 350527的情况做了下特殊处理，正在抓取数据中。希望这次能行。另外建议给重试次数设置个小一点的上限。统计局网站有很迷的访问控制策略，重试次数一多，当前ip就会被封掉一段时间～

**Comment by modood** [comment]
@vipcxj 已确认确实存在该问题，感谢 PR，已合并修复。
之前统计局一直没有访问控制策略，所以我没做重试次数处理，既然现在限制了必须得加上了，欢迎 PR :smiley:
