### ISSUE TITLE
联动没带code。。。呃。貌似还得多文件之间查。。。

### ISSUE THREAD

**Issue by xjdata** [modood/Administrative-divisions-of-China#3]
联动没带code。。。呃。貌似还得多文件之间查。。。

**Comment by modood** [comment]
您好，本项目提供的联动数据格式是大部分组件比较通用的一种，有特别格式需求的可以参考 `index.js` 文件对基础数据（省份、城市、区县、乡镇数据）进行特别的处理并导出 JSON 文件即可。

**Comment by xjdata** [comment]
谢谢.
