### ISSUE TITLE
/lib/crawler.js重试死循环 & 依赖包与OS兼容问题

### ISSUE THREAD

**Issue by z-jingjie** [modood/Administrative-divisions-of-China#31]
1. 如果/dist/保留原有2016版数据，拉取2017版数据，通过console出来的重试信息做简单的统计比对，会发现对于2017版中删去的地址，爬虫会进入死循环，建议在crawler.js中设定一个全局的retryLimit和计数器，限制重试次数

如：
> if (err.message !== 'timeout') console.log(`抓取地级（${cCode}）的县级数据失败（${err}），正在重试...`)
return exports.fetchAreas(cCode)

可考虑改为

> if (err.message !== 'timeout') {
      console.log(`抓取地级（${cCode}）的县级数据失败（${err}），正在重试...`)
      retry += 1
    }
    if (retry < retryLimit) {
      return exports.fetchAreas(cCode)
    } else {
      retry = 0
    }

2. sqlite3依赖包只能在windows环境下安装，在mac或linux环境下安装会报错

**Comment by modood** [comment]
1.  第一点其实目前是特意这样做的，如果设置超过了限制重试次数就跳过的话会导致最终的抓取到的数据可能是不完整的，而如果程序能完整地跑完没有任何报错，也不陷入死循环，说明数据才是比较正确的。所以陷入死循环后，你可以把这个错误发出来我看一下是什么原因，看是否需要进行特殊处理。
2.  第二点环境安装的问题你可以查一下相关资料，并且我个人长期以来都是 Linux 下开发，这个问题肯定是不存在的。

**Comment by modood** [comment]
#28
