### ISSUE TITLE
2017年最新统计已出

### ISSUE THREAD

**Issue by ChildLee** [modood/Administrative-divisions-of-China#32]
2017年统计用区划代码和城乡划分代码(截止2017年10月31日)
http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2017/index.html

**Comment by modood** [comment]
@ChildLee :+1: 感谢提醒，这几天我会尽快更新上

**Comment by modood** [comment]
数据已更新：`2017年统计用区划代码和城乡划分代码（截止时间：2017-10-31，发布时间：2018-06-20）`
