### ISSUE TITLE
最新的v2.1版本的东莞市对应的area表没有数据，统计局那边是有的

### ISSUE THREAD

**Issue by ZZQjavaweb** [modood/Administrative-divisions-of-China#33]

**Comment by ZZQjavaweb** [comment]
广东省中山市也是

**Comment by ZZQjavaweb** [comment]
// 特殊处理：广东省中山市（3320）、广东省东莞市（4419）、海南省儋州市（4604）没有县级。
      //if (['4420', '4419', '4604'].includes(cityCode)) continue

**Comment by ZZQjavaweb** [comment]
这个注释了也没用

**Comment by ZZQjavaweb** [comment]
额，我自己修改worker.js抓取失败，希望作者改一下

**Comment by modood** [comment]
@ZZQjavaweb  您好，中山市和东莞市比较特殊，这里是单独处理的。

因为中山市和东莞市没有 “区县” 级行政区划，目前的处理是以父级 “城市” 填充。

比如和广州市作为对比：

| 省份 | 城市 | 区县 | 乡镇 |
|:-------|:-------|:------:|:-------|
| 广东省 | 广州市 | 花都区 | 花山镇 |
| 广东省 | 中山市 |- | 横栏镇 |
| 广东省 | 东莞市 |- | 大朗镇 |

**Comment by ZZQjavaweb** [comment]
好的，明白了

**Comment by ZZQjavaweb** [comment]
好的，明白了
