### ISSUE TITLE
纠错

### ISSUE THREAD

**Issue by starbit** [modood/Administrative-divisions-of-China#35]
对比民政部最新数据 http://www.mca.gov.cn/article/sj/xzqh/2018/201804-12/20180608021501.html
有几个地方需要更新：

福建福州市：
长乐市 -> 长乐区

西藏拉萨：
达孜县 -> 达孜区

西藏：
那曲地区 -> 那曲市
那曲县 -> 色尼区

陕西咸阳：
彬县 -> 彬州市

新疆新增：
北屯市
双河市
可克达拉市
昆玉市

**Comment by modood** [comment]
参考 #21
