### ISSUE TITLE
抓取县级数据不完整

### ISSUE THREAD

**Issue by whahuzhihao** [modood/Administrative-divisions-of-China#37]
像东营市的区列表里， 市辖区没有超链接，就不会被抓取到。这种正常吗？
[http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2017/37/3705.html](url)

**Comment by modood** [comment]
@whahuzhihao 你好，这是正常的。参考 #12 
而有一些地址不是叫市辖区也没有超链接，说明该地址确实没有下级了。
比如： 福建省 -> 泉州市 -> 金门县
http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2017/35/3505.html

**Comment by whahuzhihao** [comment]
好的
