### ISSUE TITLE
运行build出错

### ISSUE THREAD

**Issue by Ben199011** [modood/Administrative-divisions-of-China#44]
"build": "npm run csv && npm run json && npm run format",当我
![build](https://user-images.githubusercontent.com/30291896/52045932-82ae1880-2580-11e9-973b-b5dd7647221e.jpg)
运行npm run build时会报.不是内部命令

**Comment by modood** [comment]
@Ben199011 你好，`npm run build` 主要是用来生成 json 格式和 csv 格式的数据
其中所运行的这两个是 shell 脚本，**暂不支持 Windows**：

*   [export_json.sh](https://github.com/modood/Administrative-divisions-of-China/blob/master/export_json.sh)
*   [export_csv.sh](https://github.com/modood/Administrative-divisions-of-China/blob/master/export_csv.sh)
