### ISSUE TITLE
你好，可以加入“华东、华中”以及南方、北方这种大的区域吗？

### ISSUE THREAD

**Issue by solider245** [modood/Administrative-divisions-of-China#45]
你好，可以加入“华东、华中”以及南方、北方这种大的区域吗？

如题，我觉得这个挺有意思的。但是目前找不到类似的库

**Comment by Veitor** [comment]
个人感觉自行实现比较好吧。。

行政区域划分个人认为属于半个政治概念，各种系统平台中的数据信息会与其关联，并且几乎都会遵守官方的相关规则（如统计局、民政部等发布的区域编码规则等）。。如今官方定义行政区划第一级为`省、自治区、直辖市、特别行政区`，那最好这么遵守，保持官方对行政区划的clean，而不要做任何修改，以便后续与官方数据同步、且区划意义上无歧义。

中国最早设立大区目的出于经济、政治、军事等管理问题。。根据当时的目的进行不断调整。上世纪50年代大区的撤销已成为事实，但不妨碍后人继续使用这个大区概念。。由于大区概念已无官方定义，夸张一点你甚至可以把东北省划分到华南片区，如果出于业务上对大区的定义，你可以自行在该库的基础上做扩展，而不是修改该库。

**Comment by modood** [comment]
暂无计划
