### ISSUE TITLE
没有610121对应的陕西省西安市长安县

### ISSUE THREAD

**Issue by FindDream** [modood/Administrative-divisions-of-China#50]
610121 陕西省西安市长安县

**Comment by modood** [comment]
@FindDream 您好，数据以国家统计局公布的最新数据为准。

> 2002年6月2日，经国务院批准撤销长安县，设立长安区。

参考链接：
*   [西安市人民政府 - 行政区划](http://www.xa.gov.cn/fqgg/cfgk/hzgg/624847.htm)
*   [国家统计局 - 2018年统计用区划代码 - 陕西省西安市](http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/61/6101.html)
