### ISSUE TITLE
那个，弱弱的问一下，怎么跑起来啊。。。

### ISSUE THREAD

**Issue by chi-bin** [modood/Administrative-divisions-of-China#51]
想试着运行一下这个爬虫，也装了node.js但是不知道咋运行。。。求大佬带带弱鸡。。

**Comment by Lizhooh** [comment]
无语，看 package 的 script

**Comment by huazai-1994** [comment]
@chi-bin 你之前怎么跑起来的？

**Comment by liyu253178** [comment]
> 想试着运行一下这个爬虫，也装了node.js但是不知道咋运行。。。求大佬带带弱鸡。。

我也不会啊，兄弟带带我

**Comment by chi-bin** [comment]
那啥，，npm install 了之后 npm run fetch 就可以了。。。。之前过于菜，给各位大佬添麻烦了。。。。。

**Comment by chi-bin** [comment]
你好


cnpm install，然后npm run fetch






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"书南"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月8日(星期三) 上午9:34
收件人:&nbsp;"modood/Administrative-divisions-of-China"<Administrative-divisions-of-China@noreply.github.com&gt;;
抄送:&nbsp;"各帅帅"<1787040716@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [modood/Administrative-divisions-of-China] 那个，弱弱的问一下，怎么跑起来啊。。。 (#51)





  
想试着运行一下这个爬虫，也装了node.js但是不知道咋运行。。。求大佬带带弱鸡。。
  
我也不会啊，兄弟带带我

**Comment by Miefind** [comment]
> 那啥，，npm install 了之后 npm run fetch 就可以了。。。。之前过于菜，给各位大佬添麻烦了。。。。。

对node版本有有要求吗？
