### ISSUE TITLE
pca-code.json 地区缺失太多，比如昆玉市

### ISSUE THREAD

**Issue by STShenZhaoliang** [modood/Administrative-divisions-of-China#53]

**Comment by xiangyuecn** [comment]
嗯，统计局的数据 新疆是丢了4个市，北屯市、双河市、可克达拉市、昆玉市。

另，由于统计局的数据是2018年底的，19-01月山东 莱芜市 被撤销，拆成莱芜区和钢城区 归 济南市了，统计局的数据滞后。

我前段时间我的库更新数据数据，对比了一下民政局06-21的数据，发现就这么几个是不同的，其他的都是相同的。供参考。

**Comment by modood** [comment]
@xiangyuecn 感谢解答 :100: 

**国家统计局数据确实是滞后于民政部数据的**
国家统计局（stats）的数据每年发布一次，而民政部（mca）每个月都会发布[变更情况](http://www.mca.gov.cn/article/sj/xzqh/2018/) ，但是这里边的数据太零碎了不好抓取，因此目前都是仅抓取每年发布的稳定版本，暂时无法与 mca 实时同步。（参考 #21）
