### ISSUE TITLE
国际化i18n

### ISSUE THREAD

**Issue by sherry1026** [modood/Administrative-divisions-of-China#54]
你好，请问怎样能拿到国际化的数据？

**Comment by modood** [comment]
@sherry1026 你好，本项目暂时无法提供国际化数据。

不过如果你的需求不是十分严格的话，你可以使用一些开源库取汉字拼音即可。

**Comment by hsxfjames** [comment]
直接取拼音是不严谨的，就我所知的 Bao'an 跟 Baoan 不是同一个地名。感觉应该会在哪里有地名翻译列表，大家一起找找

**Comment by fawdlstty** [comment]
很多城市英文名不止一个，比如
北京beijing、peking
澳门macao、macau
