### ISSUE TITLE
能不能带上地理位置信息

### ISSUE THREAD

**Issue by lshabcd** [modood/Administrative-divisions-of-China#56]
能不能带上地理位置信息？有需求根据当前GPS坐标判断在哪个省市区位置。

**Comment by xiangyuecn** [comment]
emmm..... 可以自己去高德地图采集城市边界，省市区三级的数据只有少部分采集不到😂 因为我采过😁

> 未采集到边界的有160条以内。关于未获取到坐标或边界的城市，本采集方案采取不处理策略，空着就空着，覆盖主要城市和主要人群，未覆盖区域实际使用过程中应该进行降级等处理。比如：尽最大可能的根据用户坐标来确定用户所在城市，因为存在没有边界信息的区域，未匹配到的应使用ip等城市识别方法。
> 
> 数据参考：
> https://github.com/xiangyuecn/AreaCity-JsSpider-StatsGov/blob/a25b80cb0a48d5c1e03c696fc89507b4ff261584/README.md#L159-L160

**Comment by 88250** [comment]
我用百度地图整理了下，仅供参考 https://github.com/88250/city-geo

**Comment by modood** [comment]
暂无计划，感兴趣的可以关注楼上发布的项目
