### ISSUE TITLE
pca-code.json部分数据错误

### ISSUE THREAD

**Issue by AdrianDuan** [modood/Administrative-divisions-of-China#57]
在pca-code.json三级数据中，部分数据有误，出现了乡级地区的数据，如code为4604的儋州市，它的children为乡级行政区，看了一下国家民政部的网站，它没有县（区）级行政区，所以我认为把三级的children改为460400儋州市会更合理。
同理类似的还有4419东莞等其他没有县级行政区的市级行政区

**Comment by modood** [comment]
@AdrianDuan  你好，感谢你对本项目的关注，你很细心👍👍

目前国家统计局对数据确实有一些是特殊的，因此为了尽可能地细化，对这部分数据进行了特殊处理。

目前所知的特殊数据：

*   广东省中山市（3320）、广东省东莞市（4419）、海南省儋州市（4604）没有县级，下来直接乡级
*   甘肃省嘉峪关市下仅一个县级名为市辖区（code: 620201），底下有乡级
*   福建省泉州市金门县（350527）没有乡级，也没有村级

当前所做的特殊处理：

*   `pca-code.json` 三级联动数据会将中山市、东莞市、儋州市、嘉峪关市的县级以乡级数据填充
*   `pcas-code.json` 四级联动数据会将中山市、东莞市、儋州市、嘉峪关市的县级以市级数据填充（即跟你建议的一样）
*   金门县到乡级和村级填充都是金门县

更多细节可参考源码。

相关 issue: #11

**Comment by AdrianDuan** [comment]
多谢您的解答，之前没有找到类似的issue😂 我只是无意中发现在选择的时候发现海南省儋州市下的县级数据有点奇怪，还有一个学院，然后仔细查了一下发现其实是乡级数据
