### ISSUE TITLE
请问一下 跑完fetch以后 新数据是在哪里获取的呢？

### ISSUE THREAD

**Issue by zzkuai** [modood/Administrative-divisions-of-China#58]
模块安装好以后 跑完fetch脚本后 不知道最新的数据是存在哪里了 希望解答一下 谢谢。

**Comment by modood** [comment]
@zzkuai 你好，fetch 完成后的数据存储在本地数据库中（dist/data.sqlite），有很多 UI 工具可以打开查看（例如 [sqlitebrowser](https://github.com/sqlitebrowser/sqlitebrowser)），你也可以自己将数据迁移到其他数据库管理系统中（MySQL, Oracle, MSSQL 等）。

**Comment by zzkuai** [comment]
> @zzkuai 你好，fetch 完成后的数据存储在本地数据库中（dist/data.sqlite），有很多 UI 工具可以打开查看（例如 [sqlitebrowser](https://github.com/sqlitebrowser/sqlitebrowser)），你也可以自己将数据迁移到其他数据库管理系统中（MySQL, Oracle, MSSQL 等）。

非常感谢你的回复。
我这边有安装SQLiteStudio可视化工具查看 但是里面的数据好像还是我clone下来的data.sqlite里面的数据。
请问一下我这边是遗漏了什么步骤吗，以及如何导出成pca-code.json这样的文件呢。
谢谢。

**Comment by modood** [comment]
> > @zzkuai 你好，fetch 完成后的数据存储在本地数据库中（dist/data.sqlite），有很多 UI 工具可以打开查看（例如 [sqlitebrowser](https://github.com/sqlitebrowser/sqlitebrowser)），你也可以自己将数据迁移到其他数据库管理系统中（MySQL, Oracle, MSSQL 等）。
> 
> 非常感谢你的回复。
> 我这边有安装SQLiteStudio可视化工具查看 但是里面的数据好像还是我clone下来的data.sqlite里面的数据。
> 请问一下我这边是遗漏了什么步骤吗，以及如何导出成pca-code.json这样的文件呢。
> 谢谢。

除了 `npm run fetch` 以外，还可以运行其他的脚本，脚本列表可以看 [package.json](https://github.com/modood/Administrative-divisions-of-China/blob/master/package.json#L6-L14)  文件：

```
  "scripts": {
    "test": "eslint . && mocha -t 5000",
    "fetch": "node lib/fetch.js",
    "csv": "./export_csv.sh",
    "json": "./export_json.sh",
    "format": "node lib/build.js",
    "build": "npm run csv && npm run json && npm run format",
    "precommit": "npm test"
  },
```

例如：导出 pca-code.json 这样的文件，运行的是 `npm run format`，具体做了什么事情可以查看代码 lib/build.js 文件。

**Comment by zzkuai** [comment]
> > > @zzkuai 你好，fetch 完成后的数据存储在本地数据库中（dist/data.sqlite），有很多 UI 工具可以打开查看（例如 [sqlitebrowser](https://github.com/sqlitebrowser/sqlitebrowser)），你也可以自己将数据迁移到其他数据库管理系统中（MySQL, Oracle, MSSQL 等）。
> > 
> > 
> > 非常感谢你的回复。
> > 我这边有安装SQLiteStudio可视化工具查看 但是里面的数据好像还是我clone下来的data.sqlite里面的数据。
> > 请问一下我这边是遗漏了什么步骤吗，以及如何导出成pca-code.json这样的文件呢。
> > 谢谢。
> 
> 除了 `npm run fetch` 以外，还可以运行其他的脚本，脚本列表可以看 [package.json](https://github.com/modood/Administrative-divisions-of-China/blob/master/package.json#L6-L14) 文件：
> 
> ```
>   "scripts": {
>     "test": "eslint . && mocha -t 5000",
>     "fetch": "node lib/fetch.js",
>     "csv": "./export_csv.sh",
>     "json": "./export_json.sh",
>     "format": "node lib/build.js",
>     "build": "npm run csv && npm run json && npm run format",
>     "precommit": "npm test"
>   },
> ```
> 
> 例如：导出 pca-code.json 这样的文件，运行的是 `npm run format`，具体做了什么事情可以查看代码 lib/build.js 文件。

好的 非常感谢.

**Comment by bigrotor187** [comment]
> > > @zzkuai 你好，fetch 完成后的数据存储在本地数据库中（dist/data.sqlite），有很多 UI 工具可以打开查看（例如 [sqlitebrowser](https://github.com/sqlitebrowser/sqlitebrowser)），你也可以自己将数据迁移到其他数据库管理系统中（MySQL, Oracle, MSSQL 等）。
> > 
> > 
> > 非常感谢你的回复。
> > 我这边有安装SQLiteStudio可视化工具查看 但是里面的数据好像还是我clone下来的data.sqlite里面的数据。
> > 请问一下我这边是遗漏了什么步骤吗，以及如何导出成pca-code.json这样的文件呢。
> > 谢谢。
> 
> 除了 `npm run fetch` 以外，还可以运行其他的脚本，脚本列表可以看 [package.json](https://github.com/modood/Administrative-divisions-of-China/blob/master/package.json#L6-L14) 文件：
> 
> ```
>   "scripts": {
>     "test": "eslint . && mocha -t 5000",
>     "fetch": "node lib/fetch.js",
>     "csv": "./export_csv.sh",
>     "json": "./export_json.sh",
>     "format": "node lib/build.js",
>     "build": "npm run csv && npm run json && npm run format",
>     "precommit": "npm test"
>   },
> ```
> 
> 例如：导出 pca-code.json 这样的文件，运行的是 `npm run format`，具体做了什么事情可以查看代码 lib/build.js 文件。

楼主你好，我也遇到同样的问题，我是将 crawler.js 中的省、市长度改为 6 位，run 完 yarn、npm run fetch 这两个命令之后，发现 data.sqlite 中的数据还是原来 clone 下来的那份数据。不知道是不是还需要特殊配置呢？

**Comment by modood** [comment]
@bigrotor187 最简单的，把数据全删除了，然后重新爬数据。

```bash
# 删除现有的数据
rm dist/*.csv && rm dist/[a-z]*.json && rm dist/data.sqlite && touch dist/data.sqlite

# 拉数据
npm run fetch

# 格式化 json csv 和联动数据等
npm run build
```

**Comment by bigrotor187** [comment]
> @bigrotor187 最简单的，把数据全删除了，然后重新爬数据。
> 
> ```shell
> # 删除现有的数据
> rm dist/*.csv && rm dist/[a-z]*.json && rm dist/data.sqlite && touch dist/data.sqlite
> 
> # 拉数据（这个步骤比较耗时）
> npm run fetch
> 
> # 格式化 json csv 和联动数据等
> npm run build
> ```

好的，谢谢🙏
