### ISSUE TITLE
pc开头的文件

### ISSUE THREAD

**Issue by wblbird** [modood/Administrative-divisions-of-China#59]
弱弱的问下，这些文件是什么文件啊？
pc-code.json 
pc.json 
pca-code.json 
pca.json 
pcas-code.json ago
pcas.json 
打开看了，貌似压缩版的省市县区文件？

**Comment by modood** [comment]
@wblbird 你好，可能你没仔细看首页的介绍

| 文件列表                     | JSON | CSV |
|:-----------------------------|:-----|:----|
| 省级（省份、直辖市、自治区） | [provinces.json](https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/provinces.json) | [provinces.csv](https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/provinces.csv) |
| 地级（城市）                 | [cities.json](https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/cities.json) | [cities.csv](https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/cities.csv) |
| 县级（区县）                 | [areas.json](https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/areas.json) | [areas.csv](https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/areas.csv) |
| 乡级（乡镇、街道）           | [streets.json](https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/streets.json) | [streets.csv](https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/streets.csv) |
| 村级（村委会、居委会）       | [villages.json](https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/villages.json) | [villages.csv](https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/villages.csv) |

| 文件列表                                    | 普通 | 带编码 |
|:--------------------------------------------|:-----|:-------|
| “省份、城市” 二级联动数据                   | [pc.json](https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/pc.json) | [pc-code.json](https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/pc-code.json) |
| “省份、城市、区县” 三级联动数据             | [pca.json](https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/pca.json) | [pca-code.json](https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/pca-code.json) |
| “省份、城市、区县、乡镇” 四级联动数据       | [pcas.json](https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/pcas.json) | [pcas-code.json](https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/pcas-code.json) |
| “省份、城市、区县、乡镇、村庄” 五级联动数据 | - | - |

**Comment by wblbird** [comment]
尴尬了，谢谢啊

**Comment by w15565133664** [comment]
草你妈
在2020年02月14日 11:14，wblbird 写道：

Closed #59.

**Comment by wblbird** [comment]
这位兄台，为何满嘴喷粪

**Comment by w15565133664** [comment]
草泥马，能不能别总给我转发这玩意
在2020年02月14日 11:24，wblbird 写道：

这位兄台，为何满嘴喷粪

**Comment by wblbird** [comment]
我就close个issue而已，我都不知道你谁，你自己关注什么吧，傻X

**Comment by modood** [comment]
> 草泥马，能不能别总给我转发这玩意 在2020年02月14日 11:24，wblbird 写道： 这位兄台，为何满嘴喷粪 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

@w15565133664 这位兄台，不想收到订阅消息，麻烦点右上角 `Unwatch`，然后点击 `Not watching` 即可。

![image](https://user-images.githubusercontent.com/11327898/74499199-f158dc80-4f1d-11ea-8a0f-27150de61aa5.png)
