### ISSUE TITLE
五级联动数据

### ISSUE THREAD

**Issue by lxgend** [modood/Administrative-divisions-of-China#67]
感谢您的开发，
有点好奇，是否有计划做“省份、城市、区县、乡镇、村庄” 五级联动数据？

**Comment by modood** [comment]
@lxgend 你好，五级数据都已经有了，你可以[迁移存储到数据库](https://github.com/modood/Administrative-divisions-of-China#%E6%95%B0%E6%8D%AE%E5%BA%93%E6%94%AF%E6%8C%81)。由于第五级数据比较多，业务上要实现联动功能，建议是由后端提供 API 接口，选中各级之后加载对应的子级数据即可，这样不用全量地加载数据。
