### ISSUE TITLE
市级多余/错误数据

### ISSUE THREAD

**Issue by bbgw** [modood/Administrative-divisions-of-China#70]
### 现象
```console
// 排除正确的市级地名
sqlite> select city.name, province.name from city \
   left join province \
   where city.name not like "%市%" \
      and city.name not like "%自治州%" \
      and city.name not like "%地区%" \
      and city.name not like "%盟%" \
      and city.provinceCode = province.code;                                                             
省直辖县级行政区划|河南省
省直辖县级行政区划|湖北省
省直辖县级行政区划|海南省
县|重庆市
自治区直辖县级行政区划|新疆维吾尔自治区
```
可以看到数据有多余。

### Reference
1. #42 

PS. 借机感谢分享的劳动成果！

**Comment by modood** [comment]
@bbgw 你好，你很细心，感谢指出 😁这些数据数据确实存在，目前存到 sqlite 中的都是原始数据，因为这些市级数据底下包含县级，因此不能简单地把它们过滤掉，例如：[海南省](http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2019/46.html)。

你可以根据你的应用场景对数据进行恰当地处理，例如我在导出省市二级联动数据时会把这些名字没有太大参考性的市级过滤掉，以其县级数据补进。【[参考代码](https://github.com/modood/Administrative-divisions-of-China/blob/master/lib/format.js#L8-L47)】

处理前的海南省市级数据：
```
[
  "海口市",
  "三亚市",
  "三沙市",
  "儋州市",
  "省直辖县级行政区划"
]
```

处理后的海南省市级数据：[dist/pc.json](https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/pc.json)

```
[
  "海口市",
  "三亚市",
  "三沙市",
  "儋州市",
  "五指山市",
  "琼海市",
  "文昌市",
  "万宁市",
  "东方市",
  "定安县",
  "屯昌县",
  "澄迈县",
  "临高县",
  "白沙黎族自治县",
  "昌江黎族自治县",
  "乐东黎族自治县",
  "陵水黎族自治县",
  "保亭黎族苗族自治县",
  "琼中黎族苗族自治县"
]
```
