### ISSUE TITLE
feat: 通过 Github Action 把数据发布到 Github Release

### ISSUE THREAD

**Issue by axetroy** [modood/Administrative-divisions-of-China#74]
目前下载文件都是从 master 分支下载

这样无法统计下载数量，并且不知道什么时候 master 分支变更

可以写个 Github Action，当通过 `git push --tags` 发布新版本是，自动上传文件到 Github Release

这样人们从 Github Release 下载，并且还可以追踪下载量

**Comment by modood** [comment]
暂时追踪下载量的需求
