### ISSUE TITLE
建议村数据按省分，感觉数据量有点大

### ISSUE THREAD

**Issue by wudimeicom** [modood/Administrative-divisions-of-China#77]
create table villages_64 as select * from villages where provinceCode='64';
ALTER TABLE `villages_64` ADD PRIMARY KEY( `code`);
create table villages_65 as select * from villages where provinceCode='65';
ALTER TABLE `villages_65` ADD PRIMARY KEY( `code`);

**Comment by modood** [comment]
可以根据具体需求自定义即可
