### ISSUE TITLE
能否提供抓取到五级乡村的功能？

### ISSUE THREAD

**Issue by dev-kang** [modood/Administrative-divisions-of-China#8]
只能抓取到四级，能否提供抓到乡村的功能，可能抓取时间会比较长。

**Comment by modood** [comment]
第五级行政区划实际上详细到居委会了，对于一般需求来说用处不大，但是**数据量极大**，因此暂时不考虑。

**Comment by modood** [comment]
@dev-kang 您好，最近一次更新已经支持第五级数据了，详情请看 README 文件。
