### ISSUE TITLE
省、市、县行政区划代码行政部都是统一六位数字的，建议省份、地级市也跟县一样维护成六位数字

### ISSUE THREAD

**Issue by bigrotor187** [modood/Administrative-divisions-of-China#81]
http://www.mca.gov.cn/article/sj/xzqh/2020/2020/202003301019.html

**Comment by bigrotor187** [comment]
这里可能不关心编码，只关心对应的哪些省市区，除了一些基金、证券公司什么会要求上送 6 位编码，所以先关闭吧。

**Comment by modood** [comment]
@bigrotor187 你好，标准的编码也不是 6 位的，民政局数据这里用 6 位只是因为它展示的数据详细到县级（6位），而省级（2位），市级（4位）如果需要展示成 6 位，只需在后面补 0 即可。同理如果你的数据要具体到乡镇街道，那就是9位了。
标准的编码参加：[统计用区划代码和城乡划分代码编制规则](http://www.stats.gov.cn/tjsj/tjbz/200911/t20091125_8667.html)
![image](https://user-images.githubusercontent.com/11327898/87635260-533d9c80-c771-11ea-8559-2c99b56927e6.png)

**Comment by bigrotor187** [comment]
谢谢，没想到关闭了还回复，这个仓库维护得很用心。给你点赞👍

**Comment by bigrotor187** [comment]
> @bigrotor187 你好，标准的编码也不是 6 位的，民政局数据这里用 6 位只是因为它展示的数据详细到县级（6位），而省级（2位），市级（4位）如果需要展示成 6 位，只需在后面补 0 即可。同理如果你的数据要具体到乡镇街道，那就是9位了。
> 标准的编码参加：[统计用区划代码和城乡划分代码编制规则](http://www.stats.gov.cn/tjsj/tjbz/200911/t20091125_8667.html)
> ![image](https://user-images.githubusercontent.com/11327898/87635260-533d9c80-c771-11ea-8559-2c99b56927e6.png)

谢谢，没想到关闭了还回复，这个仓库维护得很用心。给你点赞👍
