### ISSUE TITLE
获取csv文件失败

### ISSUE THREAD

**Issue by b395612437** [modood/Administrative-divisions-of-China#83]
npm run fetch可以成功并生成出data.sqlite.
但是npm run csv失败，提示sqlite3 command not found是为啥？

**Comment by modood** [comment]
> **How do I install SQLite on my operating system?**

> Mac: `brew install sqlite3`
> Debian / Ubuntu: `apt-get install sqlite3`
> CentOS / Fedora / RedHat: `yum install sqlite3`
