### ISSUE TITLE
请问有没有符合小程序格式的json文件

### ISSUE THREAD

**Issue by yyz20002008** [modood/Administrative-divisions-of-China#85]
很感谢这个数据 不过有没有符合小程序云数据库格式方便导入的，这个四级联动导不进去，因为格式不对。
https://raw.githubusercontent.com/modood/Administrative-divisions-of-China/master/dist/pcas-code.json

格式：
https://developers.weixin.qq.com/minigame/dev/wxcloud/guide/database/import.html
“
1、JSON 数据不是数组，而是类似 JSON Lines，即各个记录对象之间使用 \n 分隔，而非逗号；

2、JSON 数据每个键值对的键名首尾不能是 .，例如 ".a"、"abc."，且不能包含多个连续的 .，例如 "a..b"；
“

**Comment by modood** [comment]
@yyz20002008 你好，你写个脚本自己转一下数据格式即可
