### ISSUE TITLE
code是否是行政区代码？

### ISSUE THREAD

**Issue by shexiaobin** [modood/Administrative-divisions-of-China#88]
![image](https://user-images.githubusercontent.com/26622879/93727878-ebcc1f00-fbef-11ea-9dc5-e2cacb58230a.png)
这个co'dcode好像不是行政区代码

**Comment by modood** [comment]
@shexiaobin 你好，请参考：[国家统计局 - 统计用区划代码和城乡划分代码编制规则](http://www.stats.gov.cn/tjsj/tjbz/200911/t20091125_8667.html)
