### ISSUE TITLE
可否在每级城市中添加经纬度信息

### ISSUE THREAD

**Issue by OneSeven** [modood/Administrative-divisions-of-China#92]
可否在每级城市中添加经纬度信息，
或者按城市加经纬度也可以啊

**Comment by xiangyuecn** [comment]
我的那个库里面有采集的高德的城市坐标信息，还有边界坐标；不过开源的只到省市区这3级的，乡镇和村的没有

https://github.com/xiangyuecn/AreaCity-JsSpider-StatsGov

**Comment by modood** [comment]
暂无计划，感兴趣的可以关注楼上朋友发布的项目
